language: go

go:
- 1.2
- 1.3

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install mercurial
 - go get -u github.com/mitchellh/gox
 - mkdir -p $HOME/gopath/src/github.com/hashicorp
 - cd $HOME/gopath/src/github.com/hashicorp && git clone https://github.com/hashicorp/terraform.git
 - cd $HOME/gopath/src/github.com/hashicorp/terraform && make updatedeps && make dev

install:
 - go get github.com/motain/gocheck
 - go get github.com/soniah/dnsmadeeasy

script:
- go test
