language: go

go:
  - 1.2
  - 1.3

# DME_AKEY
# DME_SKEY
# DME_DOMAINID

env:
  global:
    - TF_ACC=1
    - DME_USESANDBOX='true'
    - secure: "t8nwzNKWsb7AIvraZjpqQDb4gYtT5md3Bcvkg7b8rt0QmOLfxXidKR4Q+x5Nmck/ehHAILp7VkeGeiTwtcREuMJznr6RnYzlJtNpBUHsTUNaCanRfua4hOw0EKl6xY93ULyOxsFMLdp7XgP/UkHcb3F3qknB3L4xQqZcFxogf0A="
    - secure: "froI7ZdNyP0NqjQKzdWXNCp49O3E5pDaWOayLpehcPJTmCNZnYvjkMgFyGJ6OrB5j+42qWFjXop+y0rMFFdfG1bJ9pTcVzUYWylLEVwXIPwgjlY7AgSmx1kZoVAXn3ddVqpWCbCdqPmA9Y9wxpo46aNPLZ/Csr7tMPdk09gkQ24="
    - secure: "jdoBmzWExgCrPiLtTGioxcKKpO+S9+GkIjtg1eEQn/bX3dHvKWr0pJrzFiJqN3bueAVdjfd0hU8P8a+Lo4zE0c0CExB+re7QbF1DD/z16G4ZT1P3nJUpbSNXmwYb36ao3+iM9q/Ng0CgjBOKIV/RsPtglZnoiXn9vKE6oS27rwk="

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mercurial
  - go get -u github.com/mitchellh/gox
  - mkdir -p $HOME/gopath/src/github.com/hashicorp
  - cd $HOME/gopath/src/github.com/hashicorp && git clone https://github.com/hashicorp/terraform.git
  - cd $HOME/gopath/src/github.com/hashicorp/terraform && make updatedeps && make dev

install:
 - go get github.com/motain/gocheck
 - go get github.com/soniah/dnsmadeeasy
 - go get github.com/soniah/terraform-provider-dme

script:
  - cd $HOME/gopath/src/github.com/soniah/terraform-provider-dme
  - go test -v
